---
title: "NEWS"
output: github_document
---

Updated `r format(Sys.time(), "%a %b %d %Y")`

# Superpower 0.1.0
- Added ANOVA_exact2 function as an extension of ANOVA_exact
  -Now functional across all sample sizes but does not return a dataframe of afex aov object
- Optimal alpha functions from JustifieR package added
- ANOVA_compromise function added which allows a compromise power analysis to be performed for all comparisons in a design

# Superpower 0.0.5

- Superpower_options("plot") is now set to TRUE. Plots will, by default, be printed
  -Easily reset with Superpower_options(plot = FALSE)
- plot_power has new features
  -Plots now show desired power
  -min_n is now limited; smallest min_n allowed is equal to the product of the design (e.g., '2b*2b' has a smallest min_n of 4)
- Small update to plot_power to fix minor error in original code
  -Error resulted in power estimates being ~0.1-0.5% off actual power estimate

# Superpower 0.0.4

- Added emmeans_power function
  - Documentation added to the vignette

- Small updates to the Shiny apps to fix typos

# Superpower 0.0.3

- Unequal sample size in the design is now permitted
  -Limited to the ANOVA_design and ANOVA_power functions
  
- Added estimated marginal means comparisons using `emmeans` R package.
  - `emm = TRUE` in the ANOVA_power, ANOVA_exact, and plot_power will result in emmeans being calculated
  - Default is all pairwise comparisons but this can be modified with `contrast_type` and `emm_comp` options
  
- Added global options
  - Options that have crossover between functions can now be set globally for the package
  - Includes: verbose, emm, emm_model, contrast_type, alpha_level, and plot
  - These global options can be seen with Superpower_options()

- Updated Shiny Apps  
  - Unequal n allowed for ANOVA_power
  - Added numeric input for alpha level (no longer slider)
  - Now includes emmeans options
  - kableExtra, emmeans, magrittr, and dplyr packages now needed to knit markdown file in app.