---
title: "Factorial ANCOVA Validation: Two Way Design"
output: github_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(simstudy)
library(data.table)
library(Superpower)
library(car)
library(testthat)
set.seed(19256)
```

# Simulation 1

```{r }

nsim = 5000
res_2x2a = vector()
res_2x2b = vector()
res_2x2ab = vector()
res_aov = vector()

for(i in 1:nsim){
  # Generate outcome and covariate matrix
  dt <- genCorData(
    20 * 4,
    mu = c(0, 0),
    sigma = 2.5,
    rho = .1,
    corstr = "cs",
    cnames = c("cov", "y1")
  )

# generate random treatment assignment
study1 = trtAssign(dt, 
                   n = 4, 
                   balanced = TRUE,
                   grpName = "group")

study1[, a := ifelse(group == 1 | group == 2,1,2)]

study1[, b := ifelse(group == 1 | group == 3,1,2)]
# add treatment effect
study1[, y := ifelse((group == 1 | group == 3), y1+1, y1)]
# factorize group
study1[, a := as.factor(a)]
study1[, b := as.factor(b)]
study1[, group := as.factor(group)]

study1[,.('means' = mean(y),'sd' = sd(y)), by = .(group)]
a = as.data.frame(anova(lm(y ~ cov + a*b, data = study1)))
a2 = as.data.frame(anova(lm(y ~ a*b, data = study1)))
res_aov = append(a2["b",]$`Pr(>F)`,
                   res_aov)

res_2x2a = append(a["a",]$`Pr(>F)`,
                   res_2x2a)
res_2x2b = append(a["b",]$`Pr(>F)`,
                   res_2x2b)
res_2x2ab = append(a["a:b",]$`Pr(>F)`,
                   res_2x2ab)

}

```

```{r}
des1 = ANOVA_design(design = "2b*2b", n = 20, mu = c(1, 0, 1, 0), sd = 2.5)
ANOVA_exact2(des1, verbose=FALSE)
mean(res_aov < .05)

test_that("Simulation 1", {
  # Both should be about .81
  # Check ANCOVA result
  expect_equal(mean(res_2x2a < .05), 
               ANCOVA_analytic(design = "2b*2b",
                mu = c(1,0,1,0),
                n = 20,
                sd = 2.5,
                r2 = .1^2,
                n_cov = 1,
                alpha_level = .05,
                beta_level = NULL)$main_result$power[1]/100, 
               tolerance = .01)
  
    expect_equal(mean(res_2x2b < .05), 
               ANCOVA_analytic(design = "2b*2b",
                mu = c(1,0,1,0),
                n = 20,
                sd = 2.5,
                r2 = .1^2,
                n_cov = 1,
                alpha_level = .05,
                beta_level = NULL)$main_result$power[2]/100, 
               tolerance = .01)

})

```
