---
title: "Factorial ANCOVA Validation: Two Way Design"
output: github_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(simstudy)
library(data.table)
library(Superpower)
library(car)
library(testthat)
set.seed(19256)
```

# Simulation 1

```{r }

nsim = 5000
res_2x2x2a = vector()
res_2x2x2b = vector()
res_2x2x2ab = vector()
res_2x2x2abc = vector()
res_aov = vector()

for(i in 1:nsim){
  # Generate outcome and covariate matrix
  dt <- genCorData(
    10 * 8,
    mu = c(0, 0),
    sigma = 2.5,
    rho = .33,
    corstr = "cs",
    cnames = c("cov", "y1")
  )

# generate random treatment assignment
study1 = trtAssign(dt, 
                   n = 8, 
                   balanced = TRUE,
                   grpName = "group")

study1[, a := ifelse(group %in% c(1:4),1,2)]

study1[, b := ifelse(group %in% c(2,4,6,8),2,1)]
study1[, c := ifelse(group %in% c(3,4,7,8),2,1)]
# add treatment effect
study1[, y := ifelse(a == 1, y1, y1+1)]
# factorize group
study1[, a := as.factor(a)]
study1[, b := as.factor(b)]
study1[, c := as.factor(c)]
study1[, group := as.factor(group)]

study1[,.('means' = mean(y),'sd' = sd(y)), by = .(group)]
a = suppressMessages({suppressWarnings({
  as.data.frame(afex::aov_car(y ~ cov + a * b * c + Error(1 / id),
                              factorize = FALSE,
                              include_aov = FALSE,
                              data = study1)$anova_table)
  }) })

a2 = suppressMessages({suppressWarnings({
  as.data.frame(afex::aov_car(
    y ~  a * b *c + Error(1 / id),
    factorize = FALSE,
    include_aov = FALSE,
    data = study1
  )$anova_table)
  }) })
res_aov = append(a2["a",]$`Pr(>F)`,
                   res_aov)

res_2x2x2a = append(a["a",]$`Pr(>F)`,
                   res_2x2x2a)
res_2x2x2b = append(a["b",]$`Pr(>F)`,
                   res_2x2x2b)
res_2x2x2ab = append(a["a:b",]$`Pr(>F)`,
                   res_2x2x2ab)
res_2x2x2abc = append(a["a:b:c",]$`Pr(>F)`,
                   res_2x2x2ab)

}

```

```{r}
des1 = ANOVA_design(design = "2b*2b*2b",
                    n = 10,
                    mu = c(1,1,1,1,0,0,0,0), sd = 2.5)
ex1 = ANOVA_exact2(des1, verbose=FALSE)


test_that("Simulation 1", {
  # check ANOVA result
  expect_equal(mean(res_aov < .05), ex1$main_results$power[2]/100,
               tolerance = .02)
  # Both should be about .81
  # Check ANCOVA result
  expect_equal(mean(res_2x2x2a < .05), 
               ANCOVA_analytic(design = "2b*2b*2b",
                mu = c(1,1,1,1,0,0,0,0),
                n = 10,
                sd = 2.5,
                r2 = .33^2,
                n_cov = 1,
                alpha_level = .05,
                beta_level = NULL)$main_results$power[1]/100, 
               tolerance = .01)
  
  expect_equal(mean(res_2x2x2b < .05), 
               ANCOVA_analytic(design = "2b*2b*2b",
                mu = c(1,1,1,1,0,0,0,0),
                n = 10,
                sd = 2.5,
                r2 = .33^2,
                n_cov = 1,
                alpha_level = .05,
                beta_level = NULL)$main_results$power[2]/100, 
               tolerance = .01)
  
  expect_equal(mean(res_2x2x2ab < .05), 
               ANCOVA_analytic(design = "2b*2b*2b",
                mu = c(1,1,1,1,0,0,0,0),
                n = 10,
                sd = 2.5,
                r2 = .33^2,
                n_cov = 1,
                alpha_level = .05,
                beta_level = NULL)$main_results$power[7]/100, 
               tolerance = .01)

})

```

