# This file is automatically generated, you probably don't want to edit this

jmvpowerOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvpowerOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            design = "2b*2w",
            labelnames = "AGE,old,young,SPEED,fast,slow",
            n = 80,
            r = 0.5,
            mu = "1.03, 1.21, 0.98, 1.01",
            sd = "1",
            plot = TRUE,
            alpha_level = 0.05,
            correction = "none",
            p_adjust = "holm",
            nsims = 100,
            comp = "cells",
            emm_model = "univariate",
            contrast_type = "pairwise",
            emm_comp = "",
            simulate = FALSE, ...) {

            super$initialize(
                package='Superpower',
                name='jmvpower',
                requiresData=FALSE,
                ...)

            private$..design <- jmvcore::OptionString$new(
                "design",
                design,
                default="2b*2w")
            private$..labelnames <- jmvcore::OptionString$new(
                "labelnames",
                labelnames,
                default="AGE,old,young,SPEED,fast,slow")
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                default=80,
                min=3)
            private$..r <- jmvcore::OptionNumber$new(
                "r",
                r,
                default=0.5)
            private$..mu <- jmvcore::OptionString$new(
                "mu",
                mu,
                default="1.03, 1.21, 0.98, 1.01")
            private$..sd <- jmvcore::OptionString$new(
                "sd",
                sd,
                default="1")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..alpha_level <- jmvcore::OptionNumber$new(
                "alpha_level",
                alpha_level,
                min=0,
                max=1,
                default=0.05)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "none",
                    "GG",
                    "HF"),
                default="none")
            private$..p_adjust <- jmvcore::OptionList$new(
                "p_adjust",
                p_adjust,
                options=list(
                    "none",
                    "holm",
                    "bonferroni",
                    "fdr",
                    "tukey",
                    "scheffe"),
                default="holm")
            private$..nsims <- jmvcore::OptionInteger$new(
                "nsims",
                nsims,
                min=100,
                max=10000,
                default=100)
            private$..comp <- jmvcore::OptionList$new(
                "comp",
                comp,
                options=list(
                    "cells",
                    "emm"),
                default="cells")
            private$..emm_model <- jmvcore::OptionList$new(
                "emm_model",
                emm_model,
                options=list(
                    "univariate",
                    "multivariate"),
                default="univariate")
            private$..contrast_type <- jmvcore::OptionList$new(
                "contrast_type",
                contrast_type,
                options=list(
                    "pairwise",
                    "poly",
                    "consec",
                    "eff"),
                default="pairwise")
            private$..emm_comp <- jmvcore::OptionString$new(
                "emm_comp",
                emm_comp,
                default="")
            private$..simulate <- jmvcore::OptionBool$new(
                "simulate",
                simulate,
                default=FALSE,
                hidden=TRUE)

            self$.addOption(private$..design)
            self$.addOption(private$..labelnames)
            self$.addOption(private$..n)
            self$.addOption(private$..r)
            self$.addOption(private$..mu)
            self$.addOption(private$..sd)
            self$.addOption(private$..plot)
            self$.addOption(private$..alpha_level)
            self$.addOption(private$..correction)
            self$.addOption(private$..p_adjust)
            self$.addOption(private$..nsims)
            self$.addOption(private$..comp)
            self$.addOption(private$..emm_model)
            self$.addOption(private$..contrast_type)
            self$.addOption(private$..emm_comp)
            self$.addOption(private$..simulate)
        }),
    active = list(
        design = function() private$..design$value,
        labelnames = function() private$..labelnames$value,
        n = function() private$..n$value,
        r = function() private$..r$value,
        mu = function() private$..mu$value,
        sd = function() private$..sd$value,
        plot = function() private$..plot$value,
        alpha_level = function() private$..alpha_level$value,
        correction = function() private$..correction$value,
        p_adjust = function() private$..p_adjust$value,
        nsims = function() private$..nsims$value,
        comp = function() private$..comp$value,
        emm_model = function() private$..emm_model$value,
        contrast_type = function() private$..contrast_type$value,
        emm_comp = function() private$..emm_comp$value,
        simulate = function() private$..simulate$value),
    private = list(
        ..design = NA,
        ..labelnames = NA,
        ..n = NA,
        ..r = NA,
        ..mu = NA,
        ..sd = NA,
        ..plot = NA,
        ..alpha_level = NA,
        ..correction = NA,
        ..p_adjust = NA,
        ..nsims = NA,
        ..comp = NA,
        ..emm_model = NA,
        ..contrast_type = NA,
        ..emm_comp = NA,
        ..simulate = NA)
)

jmvpowerResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        design = function() private$.items[["design"]],
        sims = function() private$.items[["sims"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ANOVA Power")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    summary = function() private$.items[["summary"]],
                    matrix = function() private$.items[["matrix"]],
                    plot = function() private$.items[["plot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="design",
                            title="Design")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="summary",
                            title="Design",
                            rows=4,
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="value", 
                                    `title`="", 
                                    `type`="text")),
                            clearWith=list(
                                "design",
                                "labelnames",
                                "n",
                                "sd",
                                "r",
                                "mu")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="matrix",
                            title="Correlation matrix",
                            columns=list(),
                            clearWith=list(
                                "design",
                                "labelnames",
                                "n",
                                "sd",
                                "r",
                                "mu")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="plot",
                            title="Means plot",
                            visible="(plot)",
                            renderFun=".plot",
                            clearWith=list(
                                "design",
                                "labelnames",
                                "n",
                                "sd",
                                "r",
                                "mu")))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    info = function() private$.items[["info"]],
                    main_result = function() private$.items[["main_result"]],
                    pc_results = function() private$.items[["pc_results"]],
                    emm_results = function() private$.items[["emm_results"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="sims",
                            title="Simulation")
                        self$add(jmvcore::Html$new(
                            options=options,
                            name="info",
                            content="Select 'Run simulation' from ANOVA Power's options when you are ready to perform the simulation.\n"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main_result",
                            title="Power for ANOVA Effects",
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="power", 
                                    `title`="Power"),
                                list(
                                    `name`="es", 
                                    `title`="Effect-size")),
                            clearWith=list(
                                "design",
                                "n",
                                "sd",
                                "r",
                                "mu",
                                "alpha_level",
                                "correction",
                                "labelnames",
                                "p_adjust",
                                "nsims",
                                "comp",
                                "emm_model",
                                "contrast_type",
                                "emm_p_adjust",
                                "emm_comp")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="pc_results",
                            title="Multiple comparisons",
                            visible="(comp:cells)",
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="power", 
                                    `title`="Power"),
                                list(
                                    `name`="es", 
                                    `title`="Effect-size")),
                            clearWith=list(
                                "design",
                                "n",
                                "sd",
                                "r",
                                "mu",
                                "alpha_level",
                                "correction",
                                "labelnames",
                                "p_adjust",
                                "nsims",
                                "comp",
                                "emm_model",
                                "contrast_type",
                                "emm_p_adjust",
                                "emm_comp")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="emm_results",
                            title="Power for Estimated Marginal Means",
                            visible="(comp:emm)",
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="Contrast", 
                                    `type`="text"),
                                list(
                                    `name`="power", 
                                    `title`="Power"),
                                list(
                                    `name`="es", 
                                    `title`="Cohen's f")),
                            clearWith=list(
                                "design",
                                "n",
                                "sd",
                                "r",
                                "mu",
                                "alpha_level",
                                "correction",
                                "labelnames",
                                "p_adjust",
                                "nsims",
                                "comp",
                                "emm_model",
                                "contrast_type",
                                "emm_p_adjust",
                                "emm_comp")))}))$new(options=options))}))

jmvpowerBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvpowerBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Superpower',
                name = 'jmvpower',
                version = c(1,0,0),
                options = options,
                results = jmvpowerResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' ANOVA Power
#'
#' 
#' @param design a string describing the design
#' @param labelnames a comma separated string describing the factor and level
#'   labels
#' @param n an integer specifying the sample size in each condition
#' @param r a number specifying the correlation between within-subjects
#'   variables
#' @param mu a comma separated string specifying the group means
#' @param sd a number specifying the group standard deviations
#' @param plot \code{TRUE} (default) or \code{FALSE} specifying whether to
#'   provide a means plot
#' @param alpha_level a number specifying the alpha level
#' @param correction \code{'none'} (default), \code{'GG'}, or \code{'HF'};
#'   perform no, Grennhouse-Geisser, or Huynh-Feldt sphericity correction
#'   respectively.
#' @param p_adjust the p-adjustment method to use
#' @param nsims an integer specifying the number of simulations to perform
#' @param comp .
#' @param emm_model .
#' @param contrast_type .
#' @param emm_comp .
#' @param simulate \code{TRUE} or \code{FALSE} (default); perform the
#'   simulation
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$design$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$design$matrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$design$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$sims$info} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sims$main_result} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sims$pc_results} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sims$emm_results} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
jmvpower <- function(
    design = "2b*2w",
    labelnames = "AGE,old,young,SPEED,fast,slow",
    n = 80,
    r = 0.5,
    mu = "1.03, 1.21, 0.98, 1.01",
    sd = "1",
    plot = TRUE,
    alpha_level = 0.05,
    correction = "none",
    p_adjust = "holm",
    nsims = 100,
    comp = "cells",
    emm_model = "univariate",
    contrast_type = "pairwise",
    emm_comp = "",
    simulate = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('jmvpower requires jmvcore to be installed (restart may be required)')


    options <- jmvpowerOptions$new(
        design = design,
        labelnames = labelnames,
        n = n,
        r = r,
        mu = mu,
        sd = sd,
        plot = plot,
        alpha_level = alpha_level,
        correction = correction,
        p_adjust = p_adjust,
        nsims = nsims,
        comp = comp,
        emm_model = emm_model,
        contrast_type = contrast_type,
        emm_comp = emm_comp,
        simulate = simulate)

    analysis <- jmvpowerClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
